### ISSUE TITLE
Place order before or after payment

### ISSUE THREAD

**Issue by david-fiaty-cko** [mkastaneda/magento2-paypal-express-mx#4]
Hi,
This is not an issue but a simple question.
Is the module creating the order before or after the payment has been confirmed?
Thanks a lot

**Comment by mkastaneda** [comment]
Hi, order is created after payment gets captured. This module extends magento core functionality so it works exactly the same as the Core module in terms of backend logic. This module only enables new visual improvements for Mexico implementation.

**Comment by miikEe13** [comment]
.

**Comment by miikEe13** [comment]
.
